---
packages:
  - !include esphome/nspanel_esphome_core.yaml  # The core part of NSPanel (display, PSRAM, etc.)
  - !include esphome/nspanel_esphome_standard.yaml  # The basic functionalities described on our documentation
  - !include esphome/nspanel_esphome_addon_upload_tft.yaml  # Everything you need to upload TFT to Nextion
...
